<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-checkbox</name>
   <tag></tag>
   <elementGuidId>38c1897b-b5a5-48a9-bad9-f3f5fc9a5a01</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;white&quot;]/div[@class=&quot;wrapper main&quot;]/div[@class=&quot;content-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;balances-vouchers&quot;]/div[@class=&quot;vouchers-table&quot;]/table[@class=&quot;balances-vouchers-table&quot;]/thead[1]/tr[@class=&quot;voucher-line vouchers-header&quot;]/th[@class=&quot;select-voucher&quot;]/label[@class=&quot;regular-checkbox-label&quot;]/i[@class=&quot;icon-checkbox&quot;]</value>
   </webElementProperties>
</WebElementEntity>
