<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EUR</name>
   <tag></tag>
   <elementGuidId>dcb66a72-8921-4e9f-a887-fb3a254f4237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[(text() = '
                                                                    EUR
                                                                    USD
                                                                    BTC
                                                                    BCH
                                                                    DASH
                                                                    EOS
                                                                    ETC
                                                                    ETH
                                                                    ICN
                                                                    LTC
                                                                    SMS
                                                                    VRC
                                                                    XRP
                                                            ' or . = '
                                                                    EUR
                                                                    USD
                                                                    BTC
                                                                    BCH
                                                                    DASH
                                                                    EOS
                                                                    ETC
                                                                    ETH
                                                                    ICN
                                                                    LTC
                                                                    SMS
                                                                    VRC
                                                                    XRP
                                                            ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
