<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-delete</name>
   <tag></tag>
   <elementGuidId>a9369f76-31e9-4421-a330-9bf7e0f7a9ef</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/table[1]/tbody[1]/tr[@class=&quot;api-items&quot;]/td[@class=&quot;api-key-actions clearfix&quot;]/a[@class=&quot;remove-api&quot;]/i[@class=&quot;icon-delete&quot;]</value>
   </webElementProperties>
</WebElementEntity>
