<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AprilMay</name>
   <tag></tag>
   <elementGuidId>510f702b-6bb1-4daa-979a-ab14e72f1b2f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md filter-news_from-select selectpicker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									April
									May
								</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;white&quot;]/div[@class=&quot;wrapper main&quot;]/div[@class=&quot;content-box&quot;]/div[@class=&quot;public-page&quot;]/div[@class=&quot;public-page_news&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-xs-12 filter-news_component pull-right&quot;]/div[@class=&quot;filter-news&quot;]/form[@class=&quot;filter-news_from&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7 col-xs-7 filter-news_month&quot;]/div[@class=&quot;btn-group bootstrap-select col-md filter-news_from-select open&quot;]/select[@class=&quot;col-md filter-news_from-select selectpicker&quot;]</value>
   </webElementProperties>
</WebElementEntity>
