<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Statistic</name>
   <tag></tag>
   <elementGuidId>5ea74c39-1ab7-4ea9-9e6f-3768e83d37bf</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/affiliates/statistic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Statistic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;white&quot;]/div[@class=&quot;wrapper main&quot;]/div[@class=&quot;content-box&quot;]/div[@class=&quot;content-box account-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/ul[@class=&quot;nav nav-tabs nav-justified affiliates-tab&quot;]/li[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
