<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5af2ddd75b0255dbe78b4578</name>
   <tag></tag>
   <elementGuidId>961e9548-7edf-45b4-be69-b65d6102f3a3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ticket/view/5af2ddd75b0255dbe78b4578</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#5af2ddd75b0255dbe78b4578</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/table[@class=&quot;custom ticket-table&quot;]/tbody[1]/tr[@class=&quot;viewed&quot;]/td[@class=&quot;number-col&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
