<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-checkbox</name>
   <tag></tag>
   <elementGuidId>b04356d6-fb97-4f29-b2b9-41cdbc1c6d7d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/tbody[@class=&quot;balances-vouchers-list&quot;]/tr[@class=&quot;voucher-line&quot;]/td[@class=&quot;select-voucher&quot;]/label[@class=&quot;regular-checkbox-label&quot;]/i[@class=&quot;icon-checkbox&quot;]</value>
   </webElementProperties>
</WebElementEntity>
