<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_mCS_img_loaded</name>
   <tag></tag>
   <elementGuidId>c586c1d7-9f29-43ae-9fe9-a1e86d17bee3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/svg-icons/icon-pensil.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mCS_img_loaded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/table[1]/tbody[1]/tr[@class=&quot;api-items&quot;]/td[@class=&quot;api-key-actions clearfix&quot;]/a[@class=&quot;edit-api&quot;]/img[@class=&quot;mCS_img_loaded&quot;]</value>
   </webElementProperties>
</WebElementEntity>
