<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>redeem_btn</name>
   <tag></tag>
   <elementGuidId>fd68a50f-deea-4658-8050-f07b9f01c407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>redeemPromoButton</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redeemPromoButton</value>
   </webElementProperties>
</WebElementEntity>
